# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\produce\VS Code Projects\StartPython\adva_pyqt.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 40, 741, 481))
        self.groupBox.setObjectName("groupBox")
        self.OpenFileBtn = QtWidgets.QPushButton(self.groupBox)
        self.OpenFileBtn.setGeometry(QtCore.QRect(630, 30, 81, 41))
        self.OpenFileBtn.setObjectName("OpenFileBtn")
        self.ImageLabel = QtWidgets.QLabel(self.groupBox)
        self.ImageLabel.setGeometry(QtCore.QRect(30, 40, 571, 411))
        self.ImageLabel.setObjectName("ImageLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menu.addAction(self.actionOpen)
        self.menu.addAction(self.actionExit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.OpenFileBtn.setText(_translate("MainWindow", "打开文件"))
        self.ImageLabel.setText(_translate("MainWindow", "图片展示"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.actionOpen.setText(_translate("MainWindow", "打开文件"))
        self.actionExit.setText(_translate("MainWindow", "退出"))
